### ISSUE TITLE
[교과 내용 문의] 강의 교안 ch4 slide 9 질문드립니다.

### ISSUE THREAD

**Issue by C-Seed** [JonghyeokPark/SKKU_DB_PROJECT#13]
안녕하세요 교과 내용 문의드립니다.
강의 교안 ch4 slide 9의 세번째줄에
schemas of input relations for a query are fixed (but query will run regardless of instance!)라는 
내용에서 괄호안에 있는 내용에 대해서 질문드립니다.
instance와 상관없이 query가 run된다는 것은 schemas에 해당되는 table이 실제로 있든 없든 상관없다는 뜻인가요?

**Comment by swlee69** [comment]
Regardless of instance의 의미는, 시간이 지남에 따라 table instance 의 내용이  바뀌어도, query에서 참조하는 table(s)의 스키마가 바뀌지 않는다면, query 는 동작한다는 이야기입니다.
