### ISSUE TITLE
OE 과제 3번 문항 질문있습니다.

### ISSUE THREAD

**Issue by totorottt** [JonghyeokPark/SKKU_DB_PROJECT#14]
3. 모든 고객(Customer)에 대해 "치킨"을 주문하였지만. "콜라"는 주문하지 않은 고객 번호 (customer id)를 찾아보세요.

해당 질문을 해결하기 위해 OE의 PRODUCT_INFORMATION의 product_name을 찾아보니 치킨, 콜라에 해당하는 내용이 아예 없었습니다. 모두 사무용품 관련된 product_name만 있던데, 과제를 어떻게 해결해야 하나요? 없으면 없는데로 하면 되는 건가요? 아니면 제가 잘못하고 있는 것인지요...?

**Comment by JonghyeokPark** [comment]
"치킨"과 "콜라"는 문제에서 제시한 임의의 상품명입니다. 
반드시 OE 스키마에 있는 품목에서 쿼리문을 작성할 필요 없이, 
문제에서 제시한 질의문을 SQL문과 Relational Algebra로 작성하시면 됩니다.
