### ISSUE TITLE
OE 과제 2번 문항 질문입니다.

### ISSUE THREAD

**Issue by inspirit941** [JonghyeokPark/SKKU_DB_PROJECT#15]
OE의 Orders Table에서 order_status 항목을 보니
데이터 항목 값이 NUMBERS(2)입니다. 실제로 Order Status는 1~10까지의 숫자 중 하나인데, 각 숫자의 값이 무엇을 의미하는지는 확인할 방법이 없습니다. 구글에 검색해도 제대로 나오지 않는데, '주문완료'라는 status를 의미하는 번호가 무엇인지 알 수 있는 레퍼런스가 있을까요?

**Comment by JonghyeokPark** [comment]
본 과제는 실제 OE 스키마에 있는 값을 출력해보고 확인하는 과제가 아니라, OE 스키마와 같은 OLTP 환경에서의 질의문을 SQL문과 Relational Algebra로 표현하는 것 입니다.
Order Status는 "완료" 혹은 "Complete"로 표기하면 됩니다.
