### ISSUE TITLE
[셋팅문제] 오라클 설치

### ISSUE THREAD

**Issue by seulgi-YANG** [JonghyeokPark/SKKU_DB_PROJECT#16]
가상머신에 문제가 생겨서 오라클을 다시 설치했는데
기본계정 및 테이블 설정하기 위해
@ /u01/app/oracle/product/12.2/db_1/rdbms/admin/utlsampl.sql
를 입력했는데 잘 되지 않는 것 같습니다.
어떻게 해야 하나요?
![default](https://user-images.githubusercontent.com/37572146/48109865-77eb2c80-e28c-11e8-9601-907bc57b27b7.jpeg)

**Comment by JonghyeokPark** [comment]
스크린샷이 잘 보이지 않아서, 정확한 답변이 힘듭니다.
스크린샷을 다시 올려주시기 바랍니다.

**Comment by seulgi-YANG** [comment]
안녕하세요 조교님

명륜캠퍼스에서 이상원 교수님의 데이터베이스개론 수업을 수강하는 양슬기라고 합니다.
저번 주에 오라클 세팅 문제로 찾아뵙고 문제 해결했던 학생입니다. 정말 감사드립니다.

이번 과제로 SQL Loader를 이용해 Oracle DB에 세팅하고 AR을 통해 의미있는 정보를 추출해내라는 과제를 받았는데 첨부해주신 SQL Loader ppt를 봐도 잘 이해가 되지 않아서 사용법을 여쭤보고 싶습니다.
오늘, 내일 시간이 가능하시다면 찾아뵙고 여쭤봐도 될까요?

감사합니다

양슬기올림

**Comment by JonghyeokPark** [comment]
안녕하세요. 내일 27334호로 방문해주세요.
언제쯤 방문할 예정이신가요? 1시 이후면 모두 괜찮습니다.

**Comment by seulgi-YANG** [comment]
네 조교님 안녕하세요.
그럼 1시에 찾아뵙도록 하겠습니다.

양슬기 올림

**Comment by seulgi-YANG** [comment]
조교님 안녕하세요! 
피피티와 조교님 설명을 바탕으로 외부 데이터셋을 오라클에 로딩하는 데까지 성공했습니다. 감사합니다.

그런데 여기서 유의미한 정보를 뽑아내기 위해 AR를 찾고 support, confidence를 계산하는 쿼리문을 직접 작성할 수 있어야 하는 것 같은데 교수님이 수업시간에 잘 가르쳐주시지 않은 것 같아서 어떻게 작성 하는지 모르겠습니다. a-priori 알고리즘도 개념은 이해를 했는데 이를 어떻게 적용할 수 있는지에 대해 여쭤보고 싶습니다. 혹시 시간이 가능하시다면 내일이나 월요일에 찾아뵙고 질문 드려도 될까요?
감사합니다

양슬기 올림

**Comment by seulgi-YANG** [comment]
조교님 안녕하세요!

과제 어느 정도 해결한 것 같습니다!! (제대로 한 건진 모르겠지만...)
그래서 안 찾아뵈어도 될 것 같습니다.

감사합니다.

양슬기 드림
