### ISSUE TITLE
과제 3 관련 질문입니다.

### ISSUE THREAD

**Issue by sagakjs** [JonghyeokPark/SKKU_DB_PROJECT#18]
data만들 때, 복잡한 정도나 데이터 양이 점수에 영향을 미치나요?
점수 기준이 궁금합니다.

**Comment by JonghyeokPark** [comment]
과제의 목적에 맞게 유의미한 결과를 도출하면 됩니다.
그러나, 데이터양이 단순히 row 수십개 정도 이정도면 안되고, 결과를 도출할 수 있을만큼 크면 됩니다.
아직, 데이터의 양이나 복잡한 정도에 대한 기준이 없습니다.
