### ISSUE TITLE
과제3 관련 질문입니다.

### ISSUE THREAD

**Issue by rsn0315** [JonghyeokPark/SKKU_DB_PROJECT#20]
sql loader를 사용하기 위해 열심히 찾아봤는데, 대체로 명령 프롬프트에서 sqlldr을 사용하는 방법이 나오는 것으로 확인됩니다. 그런데 명령 프롬프트에서 오라클에 접속하는 방법을 모르겠습니다.  sqlplus로 접속하려 해도 "내부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다"라는 메시지만 계속 뜹니다.

**Comment by JonghyeokPark** [comment]
혹시, 윈도우에 오라클을 설치하셨나요?
만약, Oracle VM 환경이라면 Oracle VM안에서 터미널(Terminal)창을 열고 배포해드린 예제 PPT에 있는 sqlldr 명령어를 입력하시면 실행됩니다.
오라클이 설치된 환경에서 sqlldr을 사용하셔야합니다. 
Oracle VM상에서 오라클을 설치한 상태인 경우, 윈도우 CMD창에서는 오라클 관련 명령어를 사용할 수 없습니다.

**Comment by rsn0315** [comment]
아아 감사합니다ㅠㅠ 혹시 그런데 파일 가져오려면 파일이 특정 경로에 있어야 하는 건가요? 계속 no such file or directory라고 떠서요..

**Comment by JonghyeokPark** [comment]
sqlldr을 실행시키는 현재 경로에 해당 파일이 없으면 해당 에러가 발생합니다.
data파일을 입력할때 파일명만 입력하는 것이 아니라, "절대경로"를 입력하시면 됩니다.
