### ISSUE TITLE
과제3관련 질문입니다

### ISSUE THREAD

**Issue by dlrydud99** [JonghyeokPark/SKKU_DB_PROJECT#23]
sqlldr을 쓰려면 해당 데이터가 VM에 있어야 하는거죠?? 샘플파일을 VM으로 옮기려고 했는데 안옮겨 집니다. 혹시 방법이 있나요..?

**Comment by JonghyeokPark** [comment]
제일 쉬운 방법은 VM안에 있는 FireFox 웹 브라우저를 활용해서 옮기는 것입니다. (메일, 웹에서 바로 다운로드 받기 등)
