### ISSUE TITLE
OE schema 설치 문제

### ISSUE THREAD

**Issue by helen1031** [JonghyeokPark/SKKU_DB_PROJECT#28]
![default](https://user-images.githubusercontent.com/32950301/48676601-45a2ce80-ebac-11e8-8d1b-1452273844cc.PNG)
노트북을 새로 사서 다시 OE schema를 설치하는 중입니다.
mksample.sql 스크립트 실행 도중 저렇게 문제가 발생하고 더 이상 진행이 되지 않습니다. 
명령어는 모두 정확하게 입력했습니다. 어떻게 해결할 수 있을까요

**Comment by JonghyeokPark** [comment]
mksample.sql 명령어 입력할 때 매개변수는 제대로 입력하셨나요?
경로명이 이상한 것 같습니다.

**Comment by helen1031** [comment]
네 그건 교안 그대로 입력했습니다. 제가 근데 최근에 새로 oracle db를 설치해서 버전이 12.2가 아닌데, 혹시 이게 경로명이 다른 이유가 될 수 있을까요?
