### ISSUE TITLE
[과제03] 데이터 로딩문의 

### ISSUE THREAD

**Issue by dlrydud99** [JonghyeokPark/SKKU_DB_PROJECT#29]
dat파일과 ctl파일을 만드는 것까지는 성공한 것 같은데 table row가 0개 만들어 졌다고 뜨고 select *를 해도 아무 것도 나오지 않습니다. 하지만 desc를 하면 정보가 뜨긴 뜹니다.
data파일에 있는 내용을 테이블에 옮기려면 어떻게 해야 하나요?

![default](https://user-images.githubusercontent.com/38161474/48718769-5e1ff100-ec5f-11e8-9347-8f71cbec787d.PNG)
![1](https://user-images.githubusercontent.com/38161474/48718788-6415d200-ec5f-11e8-8a8a-bc5995ab8c14.PNG)

**Comment by JonghyeokPark** [comment]
테이블이 생성만되고, 안에 있는 데이터 자체를 로딩하지 못한 결과입니다.
혹시, 1) 데이터파일이 명시한 경로에 존재하는지, 2)ctl파일에서 데이터파일의 포지션(POSITION)값과 컬럼값을 제대로 매칭했는지 확인 부탁드립니다.

**Comment by dlrydud99** [comment]
포지션 값을 정확히 어떻게 줘야 하는 것인지 잘 모르겠습니다

**Comment by JonghyeokPark** [comment]
데이터파일의 형식에 따라 다릅니다. (데이터 구분이 공백/탭으로 되어있는지 콤마(,)로 되어있는지)
아래 링크를 참고해보세요. 
http://wiki.gurubee.net/display/STUDY/SQL*Loader
