### ISSUE TITLE
과제 관련 질문입니다.

### ISSUE THREAD

**Issue by measo3** [JonghyeokPark/SKKU_DB_PROJECT#39]
쿼리문 작성하고 결과 낼 때 결과값만 같으면 쿼리문을 어떻게 작성하든지 상관없는건지 해서 질문 드립니다!

**Comment by JonghyeokPark** [comment]
문제에서 요구한 조건을 충족하고, 결과가 정답과 같으면 상관없습니다.

**Comment by measo3** [comment]
넵 감사합니다!
