### ISSUE TITLE
[Homework]

### ISSUE THREAD

**Issue by gatherheart** [JonghyeokPark/SKKU_DB_PROJECT#48]
Virtual Box의 Oracle example schema 설치 방법에 대해서 올려주신다 했는데
혹시 PPT CH0에 첨부된 github 보고 깔라는게 끝인가요?

이미 SQL LIVE로 풀고있긴한데
깔려고 해봐도 오류가 나서 못깔구 있어서요..

혹시 제대로 깔아보고싶은데 github의 설명대로 해도 
SP2-0640: Not connected
SP2-0640: Not connected
ERROR가 뜨면서 sql 파일들이 실행이 제대로 안되더라구요..

알려주시면 감사하겠습니다.

**Comment by JonghyeokPark** [comment]
PPT CH0이 "0. Oracle Installation Guide (Using Virtual Box).pdf 를 말씀하시는 것인가요?
질문해주신 내용에 스크린샷도 없고, "어떻게" 입력해서 오류가 났는지에 대한 설명이 없어서 답변이 어렵습니다.
추측하건데, @ $ORACLE_HOME/rdbms/admin/utlsample.sql 명령어를 입력하시기전에 system 계정으로 sqlplus에 제대로 접속한 것인지 확인해보세요.

**Comment by gatherheart** [comment]
앗 죄송합니다.

CH1의 10page를 보시면
https://github.com/oracle/db-sample-schemas 
링크를 들어가 다운로드 받았습니다.

샘플 스키마를 다운로드 후 

`perl -p -i.bak -e 's#__SUB__CWD__#'$(pwd)'#g' *.sql */*.sql */*.dat `
`cd db-sample-schemas/`
`sqlplus sys/oracle@localhost/orcl as sysdba`
`@mksample`

로 실행하였고 parameter 값들은 password들을 입력후  
EXAMPLE TEMP $ORACLE_HOME/demo/schema/log/ localhost:1521/orclcdb
를 넣어주었습니다.

![image](https://user-images.githubusercontent.com/40990613/55458524-2ae76880-5628-11e9-8133-9f71eb72cd33.png)

환경은 Virtual box를 깔고 Linux Oracle DB Developer VM 환경입니다.

**Comment by JonghyeokPark** [comment]
1. sample schema 설치의 경우, 동작이 지금 잘 안되는 것으로 확인이 되었습니다. 
#36  이슈를 참고하시고, HR 계정 활성화 하신 뒤 해보세요. (우선, OE account은 없는것 같습니다.)

2. Oracle LiveSQL로 과제수행하셔도 괜찮습니다. 채점할 때 감안해서 확인하도록 하겠습니다.
작성하신 쿼리에 대한 comment를 잘 남겨주세요.

3. 워드로 작성해도 무방합니다.

**Comment by gatherheart** [comment]
네 감사합니다! 
채점하시기 편하도록 최대한 깔끔하게 코멘트하도록 하겠습니다.

답변해주셔서 정말 감사하구
좋은 하루 보내세요!
