### ISSUE TITLE
과제 3번 관련 질문

### ISSUE THREAD

**Issue by doyo09** [JonghyeokPark/SKKU_DB_PROJECT#6]

**Comment by doyo09** [comment]
'''모든 고객(Customer)에 대해 “치킨”을 주문하였지만, “콜라”는 주문하지 않은 고객
번호 (customer id)를 찾아보세요.'''

3번 질문에서 <“치킨”을 주문하였지만, “콜라”는 주문하지 않은 고객> 을 어떤 테이블에서 어떤 필드에서 알 수 있을 지 너무 모호한 것 같습니다.
1, 2, 4번은 어떤 테이블 어떤 attribute를 봐야 할 지 문제에서 알 수 있었는데 3번은 제시가 안 되어 있는 것 같기도 합니다. 
과제가 성적과 관련되어 답하기 곤란하시면 어쩔 수 없지만, 하지만 아니라면 답변 주시기 바랍니다. 감사합니다. :)

**Comment by JonghyeokPark** [comment]
"치킨" 과 "콜라" 모두 "제품의 이름" 이라고 생각하시면 됩니다.

**Comment by doyo09** [comment]
답장 감사합니다! 제가 실제로 테이블들을 보려고 ORDER_ENTRY 스키마를 다운로드 하려고 하고 있습니다.
(OE계정이 없는 것 같아서요. 있다면 죄송합니다 /:) 그래서 스키마를 https://github.com/oracle/db-sample-schemas/releases/tag/v12.2.0.1 에서 다운받고 도큐먼트를 보고 다운하려고 하는데 제가 부족해서 인지 잘 안되네요.
어디서부터 잘 못 되었는지도 잘 모르겠습니다.
도큐먼트를 따라하면 이런 저런 에러들이 발생하는 데 "ORA-12514: TNS:listener does not currently know of service requested in connect descriptor" 같은 것도 생깁니다.

조교님, 죄송하지만 오라클 가상머신 환경에서 HR 스키마를 제외하고 다른 스키마들을 볼 수 있게 해주는 instruction이나 자료 있으시다면 조금 도와 주실 수 있을까요?

**Comment by JonghyeokPark** [comment]
아이캠퍼스 공지사항에 OE 스키마 설치 관련 가이드 자료 업로드 하였습니다.
