### ISSUE TITLE
Order Entry Schema 과제 질문있습니다.

### ISSUE THREAD

**Issue by totorottt** [JonghyeokPark/SKKU_DB_PROJECT#7]
Order Entry에 진입하기 위해서는 터미널에서 어떤 계정으로 로그인해야하나요?
입력해야하는 구문 알려주시면 감사하겠습니다...

**Comment by JonghyeokPark** [comment]
아이캠퍼스 공지사항에 OE 스키마 설치 관련 가이드 자료 업로드 하였습니다.
