### ISSUE TITLE
[강의] 41분반 강의 녹화

### ISSUE THREAD

**Issue by gatherheart** [JonghyeokPark/SKKU_DB_PROJECT#83]
안녕하세요 조교님

혹시 8주차부터 한국어 강의녹화가 안올라오던데 
올려주실 수 있으실까요?..

수업 내용 이해하는 큰 도움이 돼서요 
올려주시면 감사하겠습니다.

**Comment by JonghyeokPark** [comment]
학교 교육지원팀에 자동으로 수업 업로드를 부탁드렸습니다.
마침, 근로자의 날과 휴일이 겹쳐서 늦어지는 것 같습니다. 
한번 더 확인해보고, 업로드 지연이 있을 경우 다시 한번 더  요청드리겠습니다.

**Comment by gatherheart** [comment]
> 학교 교육지원팀에 자동으로 수업 업로드를 부탁드렸습니다.
> 마침, 근로자의 날과 휴일이 겹쳐서 늦어지는 것 같습니다.
> 한번 더 확인해보고, 업로드 지연이 있을 경우 다시 한번 더 요청드리겠습니다.

감사합니다!
