### ISSUE TITLE
[Homework2] 환경 셋업 설치 오류

### ISSUE THREAD

**Issue by crayonjelly** [JonghyeokPark/SKKU_DB_PROJECT#84]
#### Description

과제 피피티 9페이지의 ./setup.sh 명령어를 실행시키는 과정에서 에러가 발생합니다.
이렇게만 실행시키면 권한이 없다고 떠서 sudo를 추가해서 실행시켰는데, 캡쳐에 나온것처럼 에러가 발생합니다. 어떻게 해결할 지 도움이 필요합니다.

#### Category
[Homework]

#### Environment
Window 10, Virtual Box Oracle VM

#### Screenshot
![데베  _setup sh 에러 캡쳐](https://user-images.githubusercontent.com/22043036/57213430-c30ab000-7021-11e9-8573-ea3a1ad1207e.png)

**Comment by Csoyee** [comment]
ls -l | grep setup.sh

command 창에 위의 명령을 실행한 결과를 볼 수 있을까요?

**Comment by crayonjelly** [comment]
이렇게 뜨네요. -rwx라고 뜨는 걸 보니 execution 권한이 있는 것 같습니다

![데베  _setup sh 에러 캡쳐2](https://user-images.githubusercontent.com/22043036/57267626-b5a20400-70bb-11e9-8bd2-835aa518b09d.png)

**Comment by Csoyee** [comment]
혹시 git clone 하실 때 sudo git clone 을 하셨나요? 
> -rwx------. 1 **root root** 913 May 6 16:34 setup.sh  

위 line에서 root root 는 해당 파일을 소유하는 user 와 group 을 의미합니다. 
소유자가 root 으로 되어있어 permission error 이 뜨는 것 같습니다.

---
해결 방법 
1. SKKU_DB_PROJECT directory 를 지우고 다시 clone 합니다. 이 때 clone 시에는 sudo 명령을 붙이지 않습니다. 다시 clone 을 한뒤에 'ls -l | grep setup.sh' 를 확인해보면 user/group name 이 oracle/oinstall 로 바뀌어져 있어야 합니다.
2. chown 명령을 통해서 script 파일에 대한 user, group 을 수정해줍니다. (해당 방법의 경우 모든 script 에 대해서 수행해야 하기 때문에 1번 방법이 더 간단할 것으로 보입니다.)

**Comment by crayonjelly** [comment]
파일탐색기에서 디렉토리에 들어가서 해당 폴더를 삭제하려고 했는데 삭제할 권한이 없어 터미널에서 sudo 권한으로 삭제했습니다.
그리고 다시 clone을 하려고 했으나 권한이 없다는 메세지가 뜹니다.
시도해보면서 처음 설치를 진행하면서 처음에도 권한이 없어서 sudo로 clone 했던 기억이 있습니다.
예전에 오라클 VM의 터미널에서 위 아래 방향키로 입력했던 명령어를 띄우고 싶어서 yum, ant 등을 재설치하기도 했는데 그거때문에 환경에 이상이 생긴 것 같습니다.
오라클 VM을 삭제 후 재설치를 진행하도록 하겠습니다.
도움 감사합니다.

**Comment by crayonjelly** [comment]
재설치를 했는데 이번엔 git에 접속이 안되는 것 같습니다...
조언 부탁드립니다

![데베  _setup sh 에러 캡쳐4](https://user-images.githubusercontent.com/22043036/57278813-7935ce80-70e2-11e9-813d-0731da7251b7.png)

**Comment by Csoyee** [comment]
깃허브 주소가 틀렸습니다.
githum 라고 입력하셨습니다. 오타 확인 부탁드립니다.

**Comment by crayonjelly** [comment]
헐 감사합니다

**Comment by crayonjelly** [comment]
sqlTableCreates 에서 문제가 발생합니다. 과제파일에선 13쪽에 해당하는 부분입니다.
사진과 같이 에러가 발생하는데, 디렉토리도 틀린 게 없는 것 같습니다.
조언 부탁드립니다 ㅠ

![데베  _setup sh 에러 캡쳐5](https://user-images.githubusercontent.com/22043036/57287534-b3a76780-70f2-11e9-9e05-05892780c2f0.png)

**Comment by crayonjelly** [comment]
팀원 노트북 재설치 후 완료했습니다. 감사합니다.

**Comment by Csoyee** [comment]
setting 과정에서 문제가 많이 발생하는 것 같은데 도움을 못드려 죄송합니다.

위의 에러를 본적은 없으나 ORACLE not available 은 일반적으로 database 자체가 제대로 동작하지 않는 것이기 때문에 sqlplus scott/tiger 등을 수행했을 때 제대로 동작하는지 확인이 필요할 것 같습니다.
