### ISSUE TITLE
OE 설치 문제.

### ISSUE THREAD

**Issue by inspirit941** [JonghyeokPark/SKKU_DB_PROJECT#9]
![k-346](https://user-images.githubusercontent.com/26548454/46568772-b50a8900-c985-11e8-8ca3-73039e95f920.jpg)

처음에 perl -p 명령어를 실행하고 나서 terminal 창에 결과 반환이 안 되었는데, 맞는 건지 모르겠습니다.

@mksample oracle oracle hr oe pm ix sh bi users temp $ORACLE_HOME/demo/schema/log/ localhost/orcl

각각의 값이 'specify password for OO as parameter 숫자' 형태로 들어가는 건 알겠습니다.
그런데 저 값을 다 입력하고 나서도
![k-343](https://user-images.githubusercontent.com/26548454/46568704-79bb8a80-c984-11e8-8e9a-792bb1a7399a.jpg)

12번째 value값을 입력하라고 뜹니다.
아무것도 안 넣고 그냥 엔터 쳐서 무시하면
![k-344](https://user-images.githubusercontent.com/26548454/46568713-ab345600-c984-11e8-81af-5921e20a7dad.jpg)

no such file or directory 오류가 난 채로 진행되고, 결과적으로는 제대로 설치가 안 됩니다.

![k-345](https://user-images.githubusercontent.com/26548454/46568727-d8810400-c984-11e8-924a-3d68a7c954f0.jpg)

cmd창 실행경로는 db-sample-schemas-master로 설정한 상태입니다.

무엇이 문제인가요?

**Comment by JonghyeokPark** [comment]
perl 명령어 입력 후 , 반환이 안된 상태에서 그 다음 명령어인 sqlpus 명령어 입력하기 위해 중간에 ctrl+c를 입력해서 중단시키신 것인가요?
perl 명령어 입력후 반환되는 결과값 없이, 터미널 커서가 다음 칸으로 넘어가면 정상 수행된 것입니다.

마지막 "localhost/orcl" 이 "connect string" 입니다. (12번째 매개변수)
11번째 매개변수는 로그 파일이 저장되는 경로입니다.  "$ORACLE_HOME/demo/schema/log/" 를 11번째에 입력하시면 됩니다.

아래 명령어를 복사해서 입력하세요.
@mksample oracle oracle hr oe pm ix sh bi users temp $ORACLE_HOME/demo/schema/log/ localhost/orcl
